[package]
name = "spring-challenge-2021"
version = "0.1.0"
authors = ["Maël <mael.fortune@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"